use_frameworks!

platform :ios, '10.0'

target 'SFNetworkMonitor_Example' do
  pod 'SFNetworkMonitor', :path => '../'

  target 'SFNetworkMonitor_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
